export {default as Overview} from './Overview';
export {default as Classes} from './Classes';
export {default as Assignments} from './Assignments';
export {default as CourseMaterials} from './CourseMaterials';
export {default as Tests} from './Tests';
export {default as Attendance} from './Attendance'
export {default as Timetable} from './Timetable'
export {default as Course} from './Course'
export {default as JoinClass} from './JoinClass'